FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .

RUN chmod +x mvnw
RUN  ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]