```properties
# All connections

# connect to postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/airline_booking_db
spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD

# connect to redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Jpa/hibernate
spring.jpa.hibernate.ddl-auto=validate

# Flyway for database migration
spring.flyway.enabled=true

# Handle Spring MVC(model view controller) exceptions
# 1. tell Spring MVC to throw NoHandlerFoundException when the request endpoint does not exist
spring.mvc.throw-exception-if-no-handler-found=true

# 2. remove Spring automatic static-resource mapping so NoHandlerFoundException works
spring.web.resources.add-mappings=false


# all variable

# jwt secret and expiration time
jwt.secret=YOUR_JWT_SECRET
jwt.access-token-expiration=6000000
jwt.refresh-token-expiration=7d

# idempotency expiration
app.idempotency-expiration=1h

# Cors
app.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

# admin credential
app.admin-email=YOUR_ADMIN_EMAIL
app.admin-password=YOUR_ADMIN_PASSWORD

# rate limiting
app.window-size=3
app.count-limit=5


logging.level.org.apache.kafka.clients.NetworkClient=ERROR
```
