#connect to postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/airline_booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#connect to redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Jpa/hibernate
spring.jpa.hibernate.ddl-auto=validate

#Flyway for database migration
spring.flyway.enabled=true

#jwt secret and expiration time
jwt.secret=2E1uOv9E6zblcNUGWcKpvmkKYI5D6tJ7Rfcd2x2jsnE=
jwt.access-token-expiration=6000000
jwt.refresh-token-expiration=7d

#idempotency expiration
app.idempotency-expiration=1h

#Cors
app.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

#admin credential
app.admin-email=sam@yahoo.fr
app.admin-password=Janvier123

#Handle Spring MVC(model view controller) exceptions
#1.tell Spring MVC to throw NoHandlerFoundException when the request endpoint does not exist
spring.mvc.throw-exception-if-no-handler-found=true
#2.remove Spring automatic static-resource mapping so NoHandlerFoundException works
spring.web.resources.add-mappings=false